### ISSUE TITLE
Fails with CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by rrnewton** [facebookexperimental/hermit#49] opened 2024-04-04 15:56 UTC
**Describe the bug**

On some OS/arch/glibc, we now fail quickly with this message:

```
Fatal glibc error: CPU does not support x86-64-v2
```

**To Reproduce**

Running `examples/rand.py` is sufficient. 

**Environment**

- linux 5.12.0
- Intel(R) Xeon(R) CPU E5-2680
- glibc = stable release version 2.34.

## Initial Investigation Notes

Running with `hermit run --log=info` shows that this is an issue with arch_prctl returning EINVAL:

```
2024-04-04T15:56:54.694800Z  INFO detcore: DETLOG [syscall][detcore, dtid 3] finish syscall #3: arch_prctl(12289, 0x7fffffffd340) = Err(Errno(EINVAL))
```

**Comment by CookieComputing** [comment] 2024-04-04 18:12
Just a note when I was investigating this:

Seems like AMD hosts do not have this issue because they bypass `CPUID` interception:
```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  166
  On-line CPU(s) list:   0-165
Vendor ID:               AuthenticAMD
  Model name:            AMD EPYC-Milan Processor
$ ./hermit run date
2024-04-04T17:55:26.176575Z  WARN reverie_ptrace::perf: Pmu bugs detected: AmdSpecLockMapShouldBeDisabled
2024-04-04T17:55:26.177386Z  WARN reverie_ptrace::task: Unable to intercept CPUID: Underlying hardware does not support CPUID faulting
2024-04-04T17:55:26.178854Z  WARN reverie_ptrace::task: Unable to intercept CPUID: Underlying hardware does not support CPUID faulting
2024-04-04T17:55:26.199113Z  WARN reverie_ptrace::perf: Pmu bugs detected: AmdSpecLockMapShouldBeDisabled
2024-04-04T17:55:26.200272Z  WARN reverie_ptrace::perf: Pmu bugs detected: AmdSpecLockMapShouldBeDisabled
2024-04-04T17:55:26.204414Z  WARN reverie_ptrace::task: Unable to intercept CPUID: Underlying hardware does not support CPUID faulting
2024-04-04T17:55:26.209334Z  WARN reverie_ptrace::task: Unable to intercept CPUID: Underlying hardware does not support CPUID faulting
2024-04-04T17:55:26.245555Z  WARN reverie_ptrace::task: Unable to intercept CPUID: Underlying hardware does not support CPUID faulting
Fri Dec 31 03:59:59 PM PST 2021
2024-04-04T17:55:26.283112Z  WARN detcore::scheduler: Nondeterministic external actions [DetPid(7)] jumped in the middle of runnable work (2 tasks). Need to record this for reproducibility.
```

An Intel host, however, seems to intercept the cpuid properly and runs into the issue as described:
```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  72
  On-line CPU(s) list:   0-71
Vendor ID:               GenuineIntel
  Model name:            Intel Core Processor (Broadwell)
$ ./hermit run date
Fatal glibc error: CPU does not support x86-64-v2
```

If I run `--no-virtualize-cpuid` on the Intel host, I can confirm that it works:
```
$ ./hermit run --no-virtualize-cpuid date
Fri Dec 31 03:59:59 PM PST 2021
2024-04-04T17:58:23.540958Z  WARN detcore::scheduler: Nondeterministic external actions [DetPid(7)] jumped in the middle of runnable work (3 tasks). Need to record this for reproducibility.
```

This makes me think that the CPUID bits in [cpuid.rs](https://github.com/facebookexperimental/hermit/blob/727691fd8eb563be9f57382c3434107690d042e1/detcore/src/cpuid.rs#L41) are not toggled properly. It could, however, also be something related to [intercept_cpuid](https://github.com/facebookexperimental/reverie/blob/1711463ce369c275f7cf7fe1260675f72603661c/reverie-ptrace/src/task.rs#L619) maybe

**Comment by CookieComputing** [comment] 2024-04-11 14:18
https://github.com/facebookexperimental/hermit/commit/bd3153b4bd311831b33571d523228b2d16ff039a should close this

**Closed** 2024-04-18 19:26 UTC
Labels: bug
